name: crmapp
networks:
  crmnetwork:
services:
  mysql-db:
    container_name: app-mysql
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 1436:1433 
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=Pass@Docker$2024
    networks:
        - crmnetwork
  crm.api:
    image: ${DOCKER_REGISTRY-}crmapi
    build:
      context: .
      dockerfile: CRM.API/Dockerfile
    ports:
        - 8080:80
        - 8081:8081 
    volumes:
      - evently-oracle-data:/opt/mssql-server
  crmapp.net.develop:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: development-aspire-dashboard
    environment:
        - DB_HOST=mysql-db
        - DB_NAME= BARBER
        - DB_SA_PASSWORD=Pass@Docker$2024
    networks:
        - crmnetwork

